project_id = "dhyvufggodqkcjbrjhxk"

[functions.discover-games]
verify_jwt = false

[functions.discover-sets]
verify_jwt = false

[functions.justtcg-import]
verify_jwt = false

[functions.get-card-pricing]
verify_jwt = false

[functions.justtcg-refresh-variants]
verify_jwt = false

[functions.instant-price-check]
verify_jwt = false

[functions.price-tracker]
verify_jwt = false